/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-dim": "#0b1326",
        "on-surface-variant": "#bcc9c6",
        "on-secondary-fixed-variant": "#004395",
        "on-tertiary-fixed": "#370e00",
        "surface-container-high": "#222a3d",
        "tertiary-container": "#d27956",
        "surface-tint": "#6bd8cb",
        "on-primary-fixed": "#00201d",
        "on-surface": "#dae2fd",
        "on-secondary-fixed": "#001a42",
        "inverse-on-surface": "#283044",
        "on-primary-fixed-variant": "#005049",
        "surface-container-highest": "#2d3449",
        "inverse-primary": "#006a61",
        "background": "#0b1326",
        "on-secondary": "#002e6a",
        "on-error-container": "#ffdad6",
        "tertiary": "#ffb59a",
        "on-secondary-container": "#e6ecff",
        "tertiary-fixed-dim": "#ffb59a",
        "secondary-fixed-dim": "#adc6ff",
        "primary-container": "#29a195",
        "secondary-fixed": "#d8e2ff",
        "on-primary-container": "#00302b",
        "primary-fixed": "#89f5e7",
        "outline": "#879391",
        "on-tertiary-fixed-variant": "#773215",
        "on-background": "#dae2fd",
        "on-primary": "#003732",
        "secondary-container": "#0566d9",
        "surface-container": "#171f33",
        "surface": "#0b1326",
        "surface-variant": "#2d3449",
        "error-container": "#93000a",
        "inverse-surface": "#dae2fd",
        "on-error": "#690005",
        "error": "#ffb4ab",
        "on-tertiary-container": "#4f1700",
        "surface-bright": "#31394d",
        "tertiary-fixed": "#ffdbce",
        "primary": "#6bd8cb",
        "surface-container-lowest": "#060e20",
        "on-tertiary": "#591c02",
        "outline-variant": "#3d4947",
        "secondary": "#adc6ff",
        "primary-fixed-dim": "#6bd8cb",
        "surface-container-low": "#131b2e",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "section-gap": "64px",
        gutter: "24px",
        "container-padding-mobile": "16px",
        unit: "4px",
        "container-padding-desktop": "32px",
      },
      fontFamily: {
        "label-mono": ["JetBrains Mono", "monospace"],
        "display-lg": ["Geist", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "display-lg-mobile": ["Geist", "sans-serif"],
        "body-base": ["Inter", "sans-serif"],
      },
      fontSize: {
        "label-mono": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-sm": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-base": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
